#!/bin/bash

echo "[sslwatch] waiting for SSL setup."

until confd -onetime -node $ETCD -confdir /etc/confd/le; do
  echo "[sslwatch] SSL configuration not valid.";
  sleep 10;
done

echo "[sslwatch] SSL configuration valid - setting up watcher and requesting certs"

confd -interval 30 -node $ETCD -confdir /etc/confd/le &

tail -f /dev/null

