#!/bin/bash

set -e

source /usr/local/bin/le-fetch.conf

/usr/local/bin/le.sh --issue $DOMAINS  -w /srv/levalidate/fulcrum

exitstatus=$?
if [[ "$exitstatus" == "0" ]]; then
  echo "[le-fetch] succeeded, good job everyone."
  exit 0
else
  echo "[le-fetch] failed, waiting a bit and trying again"
fi

exit 1
