#!/bin/bash

source /usr/local/bin/le-fetch.conf

LETS_ENCRYPT_VALIDATION_CONF=/etc/nginc/conf.d/le-auth

if [[ -f $LETS_ENCRYPT_VALIDATION_CONF.off ]]; then
  cp $LETS_ENCRYPT_VALIDATION_CONF.off $LETS_ENCRYPT_VALIDATION_CONF.conf
fi

nginx -s reload


/usr/local/bin/le.sh issue /srv/levalidate/$MAIN_DOMAIN $MAIN_DOMAIN $OTHER_DOMAINS

rm $LETS_ENCRYPT_VALIDATION_CONF.conf
nginx -s reload

exitstatus=$?
if [[ "$exitstatus" == "0" ]]; then
  echo "[le-fetch] succeeded, good job everyone."
  exit 0
else
  echo "[le-fetch] failed, waiting a bit and trying again"
fi

exit 1
